# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\Abonar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbonarWindow(object):
    def setupUi(self, AbonarWindow):
        AbonarWindow.setObjectName("AbonarWindow")
        AbonarWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AbonarWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.ClienteComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ClienteComboBox.setEditable(True)
        self.ClienteComboBox.setObjectName("ClienteComboBox")
        self.gridLayout.addWidget(self.ClienteComboBox, 1, 0, 1, 1)
        self.MontoAbonoLine = QtWidgets.QLineEdit(self.centralwidget)
        self.MontoAbonoLine.setObjectName("MontoAbonoLine")
        self.gridLayout.addWidget(self.MontoAbonoLine, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AgregarAbonoButton = QtWidgets.QPushButton(self.centralwidget)
        self.AgregarAbonoButton.setObjectName("AgregarAbonoButton")
        self.horizontalLayout.addWidget(self.AgregarAbonoButton)
        self.RecargarClientesButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecargarClientesButton.setObjectName("RecargarClientesButton")
        self.horizontalLayout.addWidget(self.RecargarClientesButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        AbonarWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AbonarWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        AbonarWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AbonarWindow)
        self.statusbar.setObjectName("statusbar")
        AbonarWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AbonarWindow)
        QtCore.QMetaObject.connectSlotsByName(AbonarWindow)

    def retranslateUi(self, AbonarWindow):
        _translate = QtCore.QCoreApplication.translate
        AbonarWindow.setWindowTitle(_translate("AbonarWindow", "MainWindow"))
        self.label_2.setText(_translate("AbonarWindow", "Monto de abono:"))
        self.label.setText(_translate("AbonarWindow", "Cliente:"))
        self.AgregarAbonoButton.setText(_translate("AbonarWindow", "Agregar abono"))
        self.RecargarClientesButton.setText(_translate("AbonarWindow", "Recargar Clientes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AbonarWindow = QtWidgets.QMainWindow()
    ui = Ui_AbonarWindow()
    ui.setupUi(AbonarWindow)
    AbonarWindow.show()
    sys.exit(app.exec_())
