# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\agregarVenta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.MicaLine = QtWidgets.QLineEdit(self.centralwidget)
        self.MicaLine.setObjectName("MicaLine")
        self.gridLayout.addWidget(self.MicaLine, 5, 0, 1, 1)
        self.ModeloLine = QtWidgets.QLineEdit(self.centralwidget)
        self.ModeloLine.setObjectName("ModeloLine")
        self.gridLayout.addWidget(self.ModeloLine, 3, 0, 1, 1)
        self.ClienteCombo = QtWidgets.QComboBox(self.centralwidget)
        self.ClienteCombo.setEditable(True)
        self.ClienteCombo.setObjectName("ClienteCombo")
        self.gridLayout.addWidget(self.ClienteCombo, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.AbonoLine = QtWidgets.QLineEdit(self.centralwidget)
        self.AbonoLine.setObjectName("AbonoLine")
        self.gridLayout_2.addWidget(self.AbonoLine, 1, 1, 1, 1)
        self.CostoLine = QtWidgets.QLineEdit(self.centralwidget)
        self.CostoLine.setObjectName("CostoLine")
        self.gridLayout_2.addWidget(self.CostoLine, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.SaldoLine = QtWidgets.QLineEdit(self.centralwidget)
        self.SaldoLine.setObjectName("SaldoLine")
        self.gridLayout_2.addWidget(self.SaldoLine, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.CalendarioHoy = QtWidgets.QCalendarWidget(self.centralwidget)
        self.CalendarioHoy.setObjectName("CalendarioHoy")
        self.verticalLayout.addWidget(self.CalendarioHoy)
        self.gridLayout_3.addLayout(self.verticalLayout, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Modelo Lentes:"))
        self.label.setText(_translate("MainWindow", "Cliente:"))
        self.label_4.setText(_translate("MainWindow", "Tipo de Mica"))
        self.label_6.setText(_translate("MainWindow", "Abono:"))
        self.label_5.setText(_translate("MainWindow", "Costo:"))
        self.label_7.setText(_translate("MainWindow", "Saldo:"))
        self.label_2.setText(_translate("MainWindow", "Fecha Hoy:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
