# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\AgregarCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.NombreLine = QtWidgets.QLineEdit(self.centralwidget)
        self.NombreLine.setObjectName("NombreLine")
        self.gridLayout.addWidget(self.NombreLine, 1, 0, 1, 1)
        self.TelefonoLine = QtWidgets.QLineEdit(self.centralwidget)
        self.TelefonoLine.setObjectName("TelefonoLine")
        self.gridLayout.addWidget(self.TelefonoLine, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AgregarClienteButton = QtWidgets.QPushButton(self.centralwidget)
        self.AgregarClienteButton.setObjectName("AgregarClienteButton")
        self.horizontalLayout.addWidget(self.AgregarClienteButton)
        self.LimpiarButton = QtWidgets.QPushButton(self.centralwidget)
        self.LimpiarButton.setObjectName("LimpiarButton")
        self.horizontalLayout.addWidget(self.LimpiarButton)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.EdadLine = QtWidgets.QLineEdit(self.centralwidget)
        self.EdadLine.setObjectName("EdadLine")
        self.gridLayout.addWidget(self.EdadLine, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Teléfono"))
        self.AgregarClienteButton.setText(_translate("MainWindow", "Agregar Cliente"))
        self.LimpiarButton.setText(_translate("MainWindow", "Limpiar"))
        self.label.setText(_translate("MainWindow", "Nombre completo"))
        self.label_2.setText(_translate("MainWindow", "Edad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
