# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.AgregarVentasButton = QtWidgets.QPushButton(self.centralwidget)
        self.AgregarVentasButton.setMinimumSize(QtCore.QSize(0, 250))
        self.AgregarVentasButton.setObjectName("AgregarVentasButton")
        self.gridLayout.addWidget(self.AgregarVentasButton, 0, 1, 1, 1)
        self.AgregarClientesButton = QtWidgets.QPushButton(self.centralwidget)
        self.AgregarClientesButton.setMinimumSize(QtCore.QSize(0, 250))
        self.AgregarClientesButton.setObjectName("AgregarClientesButton")
        self.gridLayout.addWidget(self.AgregarClientesButton, 0, 0, 1, 1)
        self.AbonoClienteButton = QtWidgets.QPushButton(self.centralwidget)
        self.AbonoClienteButton.setMinimumSize(QtCore.QSize(0, 250))
        self.AbonoClienteButton.setObjectName("AbonoClienteButton")
        self.gridLayout.addWidget(self.AbonoClienteButton, 1, 0, 1, 1)
        self.AbrirClientesVentasButton = QtWidgets.QPushButton(self.centralwidget)
        self.AbrirClientesVentasButton.setMinimumSize(QtCore.QSize(0, 250))
        self.AbrirClientesVentasButton.setObjectName("AbrirClientesVentasButton")
        self.gridLayout.addWidget(self.AbrirClientesVentasButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AgregarVentasButton.setText(_translate("MainWindow", "Agregar Ventas"))
        self.AgregarClientesButton.setText(_translate("MainWindow", "Agregar Clientes"))
        self.AbonoClienteButton.setText(_translate("MainWindow", "Abono Cliente"))
        self.AbrirClientesVentasButton.setText(_translate("MainWindow", "Ver Clientes y ventas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
