# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\ClienteView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClienteViewWindow(object):
    def setupUi(self, ClienteViewWindow):
        ClienteViewWindow.setObjectName("ClienteViewWindow")
        ClienteViewWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ClienteViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        ClienteViewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClienteViewWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ClienteViewWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClienteViewWindow)
        self.statusbar.setObjectName("statusbar")
        ClienteViewWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClienteViewWindow)
        QtCore.QMetaObject.connectSlotsByName(ClienteViewWindow)

    def retranslateUi(self, ClienteViewWindow):
        _translate = QtCore.QCoreApplication.translate
        ClienteViewWindow.setWindowTitle(_translate("ClienteViewWindow", "MainWindow"))
        self.label.setText(_translate("ClienteViewWindow", "Clientes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ClienteViewWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ClienteViewWindow", "Nombre "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ClienteViewWindow", "ID venta"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ClienteViewWindow", "Producto vendido"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ClienteViewWindow", "Costo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClienteViewWindow = QtWidgets.QMainWindow()
    ui = Ui_ClienteViewWindow()
    ui.setupUi(ClienteViewWindow)
    ClienteViewWindow.show()
    sys.exit(app.exec_())
